#!/bin/bash

mkdir -p lib

# Download the create-coreos-vdi script if it doesn't exist
if [ ! -f ./lib/create-coreos-vdi ]; then
    curl https://raw.githubusercontent.com/coreos/scripts/build-1465/contrib/create-coreos-vdi > ./lib/create-coreos-vdi
    chmod +x ./lib/create-coreos-vdi
fi

# Download the create-basic-configdrive script if it doesn't exist
if [ ! -f ./lib/create-basic-configdrive ]; then
    curl https://raw.githubusercontent.com/coreos/scripts/build-1465/contrib/create-basic-configdrive > ./lib/create-basic-configdrive
    chmod +x ./lib/create-basic-configdrive
fi
